apiVersion: v1
kind: ServiceAccount
metadata:
  name: myserviceaccount
  namespace: mzz
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myserviceaccount
subjects:
  - kind: ServiceAccount
    name: myserviceaccount
    namespace: mzz
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io